wait for rechunk to get reworked

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -91,6 +91,21 @@ jobs:
           pubkey: https://raw.githubusercontent.com/ublue-os/${{ env.upstream_repo }}/main/cosign.pub
           registry: ghcr.io/ublue-os
 
+      # - name: Pull Images
+      #   uses: Wandalen/wretry.action@v3.5.0
+      #   id: pull
+      #   with:
+      #     attempt_limit: 3
+      #     attempt_delay: 15000
+      #     command: |
+      #       set -eoux pipefail
+      #       sudo podman pull ghcr.io/ublue-os/akmods:${{ env.kernel_flavor }}-${{ env.fedora_version }}
+      #       sudo podman pull ghcr.io/ublue-os/akmods-nvidia:${{ env.kernel_flavor }}-${{ env.fedora_version }}
+      #       sudo podman pull ghcr.io/ublue-os/akmods-zfs:coreos-stable-${{ env.fedora_version }}
+      #       sudo podman pull ghcr.io/ublue-os/coreos-stable-kernel:${{ env.fedora_version }}
+      #       sudo podman pull ghcr.io/ublue-os/${{ env.image }}:${{ env.tag_version }}
+      #       sudo podman pull ghcr.io/hhd-dev/rechunk:v0.5.0
+
       - name: Pull Images
         uses: Wandalen/wretry.action@v3.5.0
         id: pull
@@ -99,18 +114,18 @@ jobs:
           attempt_delay: 15000
           command: |
             set -eoux pipefail
-            sudo podman pull ghcr.io/ublue-os/akmods:${{ env.kernel_flavor }}-${{ env.fedora_version }}
-            sudo podman pull ghcr.io/ublue-os/akmods-nvidia:${{ env.kernel_flavor }}-${{ env.fedora_version }}
-            sudo podman pull ghcr.io/ublue-os/akmods-zfs:coreos-stable-${{ env.fedora_version }}
-            sudo podman pull ghcr.io/ublue-os/coreos-stable-kernel:${{ env.fedora_version }}
-            sudo podman pull ghcr.io/ublue-os/${{ env.image }}:${{ env.tag_version }}
-            sudo podman pull ghcr.io/hhd-dev/rechunk:v0.5.0
+            podman pull ghcr.io/ublue-os/akmods:${{ env.kernel_flavor }}-${{ env.fedora_version }}
+            podman pull ghcr.io/ublue-os/akmods-nvidia:${{ env.kernel_flavor }}-${{ env.fedora_version }}
+            podman pull ghcr.io/ublue-os/akmods-zfs:coreos-stable-${{ env.fedora_version }}
+            podman pull ghcr.io/ublue-os/coreos-stable-kernel:${{ env.fedora_version }}
+            podman pull ghcr.io/ublue-os/${{ env.image }}:${{ env.tag_version }}
+            # podman pull ghcr.io/hhd-dev/rechunk:v0.5.0
 
       - name: Checkout Push to Registry Action
         uses: actions/checkout@v4
 
       - name: Maximize Build Space
-        # if: matrix.image == 'bazzite-gnome-nvidia' || matrix.image == 'bazzite-deck-gnome'
+        if: matrix.image == 'bazzite-gnome-nvidia' || matrix.image == 'bazzite-deck-gnome'
         uses: ublue-os/remove-unwanted-software@v7
 
       - name: Generate Tags
@@ -136,16 +151,16 @@ jobs:
           echo "default_tag=${tag}" >> "$GITHUB_OUTPUT"
           echo "build_tags=${BUILD_TAGS[*]}" >> "$GITHUB_OUTPUT"
 
-      # - name: Image Metadata
-      #   uses: docker/metadata-action@v5
-      #   id: meta
-      #   with:
-      #     images: ${{ env.IMAGE_NAME }}
-      #     labels: |
-      #       org.opencontainers.image.title=${{ env.IMAGE_NAME }}
-      #       org.opencontainers.image.description=m2os is my OCI image built from ublue projects. It mainly extends bazzite/bluefin for my uses.
-      #       org.opencontainers.image.version=${{ env.version }}
-      #       ostree.linux=${{ env.kernel_release }}.x86_64
+      - name: Image Metadata
+        uses: docker/metadata-action@v5
+        id: meta
+        with:
+          images: ${{ env.IMAGE_NAME }}
+          labels: |
+            org.opencontainers.image.title=${{ env.IMAGE_NAME }}
+            org.opencontainers.image.description=m2os is my OCI image built from ublue projects. It mainly extends bazzite/bluefin for my uses.
+            org.opencontainers.image.version=${{ env.version }}
+            ostree.linux=${{ env.kernel_release }}.x86_64
 
       # - name: Build Image
       #   id: build_image
@@ -163,50 +178,51 @@ jobs:
       #       NVIDIA=${{ env.nvidia }}
       #     labels: ${{ steps.meta.outputs.labels }}
       #     oci: false
-      - name: Build Image
-        id: build_image
-        shell: bash
-        run: |
-          sudo buildah build \
-            --format "docker" \
-            --build-arg IMAGE=${{ env.image }} \
-            --build-arg TAG_VERSION=${{ env.tag_version }} \
-            --build-arg FEDORA_VERSION=${{ env.fedora_version }} \
-            --build-arg KERNEL_FLAVOR=${{ env.kernel_flavor }} \
-            --build-arg NVIDIA=${{ env.nvidia }} \
-            --tag raw-img .
 
-      - name: Remove old Images
-        run: |
-          set -eoux pipefail
-          sudo podman image rm ghcr.io/ublue-os/akmods:${{ env.kernel_flavor }}-${{ env.fedora_version }}
-          sudo podman image rm ghcr.io/ublue-os/akmods-nvidia:${{ env.kernel_flavor }}-${{ env.fedora_version }}
-          sudo podman image rm ghcr.io/ublue-os/akmods-zfs:coreos-stable-${{ env.fedora_version }}
-          sudo podman image rm ghcr.io/ublue-os/coreos-stable-kernel:${{ env.fedora_version }}
-          sudo podman image rm ghcr.io/ublue-os/${{ env.image }}:${{ env.tag_version }}
+      # - name: Build Image
+      #   id: build_image
+      #   shell: bash
+      #   run: |
+      #     sudo buildah build \
+      #       --format "docker" \
+      #       --build-arg IMAGE=${{ env.image }} \
+      #       --build-arg TAG_VERSION=${{ env.tag_version }} \
+      #       --build-arg FEDORA_VERSION=${{ env.fedora_version }} \
+      #       --build-arg KERNEL_FLAVOR=${{ env.kernel_flavor }} \
+      #       --build-arg NVIDIA=${{ env.nvidia }} \
+      #       --tag raw-img .
 
-      - name: Rechunk Image
-        id: rechunk
-        uses: hhd-dev/rechunk@v0.5.0
-        with:
-          ref: "localhost/raw-img"
-          prev-ref: "ghcr.io/m2giles/m2os:${{ steps.generate_tags.outputs.default_tag }}"
-          version: "${{ env.version }}"
-          rechunk: "ghcr.io/hhd-dev/rechunk:v0.5.0"
-          labels: |
-            org.opencontainers.image.title=${{ env.IMAGE_NAME }}
-            org.opencontainers.image.description=m2os is my OCI image built from ublue projects. It mainly extends bazzite/bluefin for my uses.
-            org.opencontainers.image.version=${{ env.version }}
-            ostree.linux=${{ env.kernel_release }}.x86_64
+      # - name: Remove old Images
+      #   run: |
+      #     set -eoux pipefail
+      #     sudo podman image rm ghcr.io/ublue-os/akmods:${{ env.kernel_flavor }}-${{ env.fedora_version }}
+      #     sudo podman image rm ghcr.io/ublue-os/akmods-nvidia:${{ env.kernel_flavor }}-${{ env.fedora_version }}
+      #     sudo podman image rm ghcr.io/ublue-os/akmods-zfs:coreos-stable-${{ env.fedora_version }}
+      #     sudo podman image rm ghcr.io/ublue-os/coreos-stable-kernel:${{ env.fedora_version }}
+      #     sudo podman image rm ghcr.io/ublue-os/${{ env.image }}:${{ env.tag_version }}
 
-      - name: Load into Podman and Tag
-        shell: bash
-        run: |
-          IMAGE=$(podman pull ${{ steps.rechunk.outputs.ref }})
-          sudo rm -rf ${{ steps.rechunk.outputs.output }}
-          for tag in ${{ steps.generate_tags.outputs.alias_tags }}; do
-            podman tag $IMAGE m2os:$tag
-          done
+      # - name: Rechunk Image
+      #   id: rechunk
+      #   uses: hhd-dev/rechunk@v0.5.0
+      #   with:
+      #     ref: "localhost/raw-img"
+      #     prev-ref: "ghcr.io/m2giles/m2os:${{ steps.generate_tags.outputs.default_tag }}"
+      #     version: "${{ env.version }}"
+      #     rechunk: "ghcr.io/hhd-dev/rechunk:v0.5.0"
+      #     labels: |
+      #       org.opencontainers.image.title=${{ env.IMAGE_NAME }}
+      #       org.opencontainers.image.description=m2os is my OCI image built from ublue projects. It mainly extends bazzite/bluefin for my uses.
+      #       org.opencontainers.image.version=${{ env.version }}
+      #       ostree.linux=${{ env.kernel_release }}.x86_64
+
+      # - name: Load into Podman and Tag
+      #   shell: bash
+      #   run: |
+      #     IMAGE=$(podman pull ${{ steps.rechunk.outputs.ref }})
+      #     sudo rm -rf ${{ steps.rechunk.outputs.output }}
+      #     for tag in ${{ steps.generate_tags.outputs.alias_tags }}; do
+      #       podman tag $IMAGE m2os:$tag
+      #     done
 
       - name: Check Secureboot
         id: secureboot
@@ -263,7 +279,7 @@ jobs:
       - name: Sign Container Image
         if: github.event_name != 'pull_request'
         run: |
-          cosign sign -y --key env://COSIGN_PRIVATE_KEY ${{ steps.registry_case.outputs.lowercase }}/${{ steps.build_image.outputs.image }}@${TAGS}
+          cosign sign -y --key env://COSIGN_PRIVATE_KEY ${{ steps.registry_case.outputs.lowercase }}/m2os@${TAGS}
         env:
           TAGS: ${{ steps.push.outputs.outputs && fromJSON(steps.push.outputs.outputs).digest }}
           COSIGN_EXPERIMENTAL: false
