Try rechunk again
Signed-off-by: m2Giles <69128853+m2Giles@users.noreply.github.com>

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -91,21 +91,6 @@ jobs:
           pubkey: https://raw.githubusercontent.com/ublue-os/${{ env.upstream_repo }}/main/cosign.pub
           registry: ghcr.io/ublue-os
 
-      # - name: Pull Images
-      #   uses: Wandalen/wretry.action@v3.5.0
-      #   id: pull
-      #   with:
-      #     attempt_limit: 3
-      #     attempt_delay: 15000
-      #     command: |
-      #       set -eoux pipefail
-      #       sudo podman pull ghcr.io/ublue-os/akmods:${{ env.kernel_flavor }}-${{ env.fedora_version }}
-      #       sudo podman pull ghcr.io/ublue-os/akmods-nvidia:${{ env.kernel_flavor }}-${{ env.fedora_version }}
-      #       sudo podman pull ghcr.io/ublue-os/akmods-zfs:coreos-stable-${{ env.fedora_version }}
-      #       sudo podman pull ghcr.io/ublue-os/coreos-stable-kernel:${{ env.fedora_version }}
-      #       sudo podman pull ghcr.io/ublue-os/${{ env.image }}:${{ env.tag_version }}
-      #       sudo podman pull ghcr.io/hhd-dev/rechunk:v0.5.0
-
       - name: Pull Images
         uses: Wandalen/wretry.action@v3.5.0
         id: pull
@@ -114,12 +99,27 @@ jobs:
           attempt_delay: 15000
           command: |
             set -eoux pipefail
-            podman pull ghcr.io/ublue-os/akmods:${{ env.kernel_flavor }}-${{ env.fedora_version }}
-            podman pull ghcr.io/ublue-os/akmods-nvidia:${{ env.kernel_flavor }}-${{ env.fedora_version }}
-            podman pull ghcr.io/ublue-os/akmods-zfs:coreos-stable-${{ env.fedora_version }}
-            podman pull ghcr.io/ublue-os/coreos-stable-kernel:${{ env.fedora_version }}
-            podman pull ghcr.io/ublue-os/${{ env.image }}:${{ env.tag_version }}
-            # podman pull ghcr.io/hhd-dev/rechunk:v0.5.0
+            sudo podman pull ghcr.io/ublue-os/akmods:${{ env.kernel_flavor }}-${{ env.fedora_version }}
+            sudo podman pull ghcr.io/ublue-os/akmods-nvidia:${{ env.kernel_flavor }}-${{ env.fedora_version }}
+            sudo podman pull ghcr.io/ublue-os/akmods-zfs:coreos-stable-${{ env.fedora_version }}
+            sudo podman pull ghcr.io/ublue-os/coreos-stable-kernel:${{ env.fedora_version }}
+            sudo podman pull ghcr.io/ublue-os/${{ env.image }}:${{ env.tag_version }}
+            sudo podman pull ghcr.io/hhd-dev/rechunk:latest
+
+      # - name: Pull Images
+      #   uses: Wandalen/wretry.action@v3.5.0
+      #   id: pull
+      #   with:
+      #     attempt_limit: 3
+      #     attempt_delay: 15000
+      #     command: |
+      #       set -eoux pipefail
+      #       podman pull ghcr.io/ublue-os/akmods:${{ env.kernel_flavor }}-${{ env.fedora_version }}
+      #       podman pull ghcr.io/ublue-os/akmods-nvidia:${{ env.kernel_flavor }}-${{ env.fedora_version }}
+      #       podman pull ghcr.io/ublue-os/akmods-zfs:coreos-stable-${{ env.fedora_version }}
+      #       podman pull ghcr.io/ublue-os/coreos-stable-kernel:${{ env.fedora_version }}
+      #       podman pull ghcr.io/ublue-os/${{ env.image }}:${{ env.tag_version }}
+      #       # podman pull ghcr.io/hhd-dev/rechunk:v0.5.0
 
       - name: Checkout Push to Registry Action
         uses: actions/checkout@v4
@@ -162,67 +162,68 @@ jobs:
             org.opencontainers.image.version=${{ env.version }}
             ostree.linux=${{ env.kernel_release }}.x86_64
 
-      - name: Build Image
-        id: build_image
-        uses: redhat-actions/buildah-build@v2
-        with:
-          containerfiles: |
-            ./Containerfile
-          image: ${{ env.IMAGE_NAME }}
-          tags: ${{ steps.generate_tags.outputs.build_tags }}
-          build-args: |
-            IMAGE=${{ env.image }}
-            TAG_VERSION=${{ env.tag_version }}
-            FEDORA_VERSION=${{ env.fedora_version }}
-            KERNEL_FLAVOR=${{ env.kernel_flavor }}
-            NVIDIA=${{ env.nvidia }}
-          labels: ${{ steps.meta.outputs.labels }}
-          oci: false
-
       # - name: Build Image
       #   id: build_image
-      #   shell: bash
-      #   run: |
-      #     sudo buildah build \
-      #       --format "docker" \
-      #       --build-arg IMAGE=${{ env.image }} \
-      #       --build-arg TAG_VERSION=${{ env.tag_version }} \
-      #       --build-arg FEDORA_VERSION=${{ env.fedora_version }} \
-      #       --build-arg KERNEL_FLAVOR=${{ env.kernel_flavor }} \
-      #       --build-arg NVIDIA=${{ env.nvidia }} \
-      #       --tag raw-img .
-
-      # - name: Remove old Images
-      #   run: |
-      #     set -eoux pipefail
-      #     sudo podman image rm ghcr.io/ublue-os/akmods:${{ env.kernel_flavor }}-${{ env.fedora_version }}
-      #     sudo podman image rm ghcr.io/ublue-os/akmods-nvidia:${{ env.kernel_flavor }}-${{ env.fedora_version }}
-      #     sudo podman image rm ghcr.io/ublue-os/akmods-zfs:coreos-stable-${{ env.fedora_version }}
-      #     sudo podman image rm ghcr.io/ublue-os/coreos-stable-kernel:${{ env.fedora_version }}
-      #     sudo podman image rm ghcr.io/ublue-os/${{ env.image }}:${{ env.tag_version }}
-
-      # - name: Rechunk Image
-      #   id: rechunk
-      #   uses: hhd-dev/rechunk@v0.5.0
+      #   uses: redhat-actions/buildah-build@v2
       #   with:
-      #     ref: "localhost/raw-img"
-      #     prev-ref: "ghcr.io/m2giles/m2os:${{ steps.generate_tags.outputs.default_tag }}"
-      #     version: "${{ env.version }}"
-      #     rechunk: "ghcr.io/hhd-dev/rechunk:v0.5.0"
-      #     labels: |
-      #       org.opencontainers.image.title=${{ env.IMAGE_NAME }}
-      #       org.opencontainers.image.description=m2os is my OCI image built from ublue projects. It mainly extends bazzite/bluefin for my uses.
-      #       org.opencontainers.image.version=${{ env.version }}
-      #       ostree.linux=${{ env.kernel_release }}.x86_64
+      #     containerfiles: |
+      #       ./Containerfile
+      #     image: ${{ env.IMAGE_NAME }}
+      #     tags: ${{ steps.generate_tags.outputs.build_tags }}
+      #     build-args: |
+      #       IMAGE=${{ env.image }}
+      #       TAG_VERSION=${{ env.tag_version }}
+      #       FEDORA_VERSION=${{ env.fedora_version }}
+      #       KERNEL_FLAVOR=${{ env.kernel_flavor }}
+      #       NVIDIA=${{ env.nvidia }}
+      #     labels: ${{ steps.meta.outputs.labels }}
+      #     oci: false
 
-      # - name: Load into Podman and Tag
-      #   shell: bash
-      #   run: |
-      #     IMAGE=$(podman pull ${{ steps.rechunk.outputs.ref }})
-      #     sudo rm -rf ${{ steps.rechunk.outputs.output }}
-      #     for tag in ${{ steps.generate_tags.outputs.alias_tags }}; do
-      #       podman tag $IMAGE m2os:$tag
-      #     done
+      - name: Build Image
+        id: build_image
+        shell: bash
+        run: |
+          sudo buildah build \
+            --format "docker" \
+            --build-arg IMAGE=${{ env.image }} \
+            --build-arg TAG_VERSION=${{ env.tag_version }} \
+            --build-arg FEDORA_VERSION=${{ env.fedora_version }} \
+            --build-arg KERNEL_FLAVOR=${{ env.kernel_flavor }} \
+            --build-arg NVIDIA=${{ env.nvidia }} \
+            --tag raw-img .
+
+      - name: Remove old Images
+        run: |
+          set -eoux pipefail
+          sudo podman image rm ghcr.io/ublue-os/akmods:${{ env.kernel_flavor }}-${{ env.fedora_version }}
+          sudo podman image rm ghcr.io/ublue-os/akmods-nvidia:${{ env.kernel_flavor }}-${{ env.fedora_version }}
+          sudo podman image rm ghcr.io/ublue-os/akmods-zfs:coreos-stable-${{ env.fedora_version }}
+          sudo podman image rm ghcr.io/ublue-os/coreos-stable-kernel:${{ env.fedora_version }}
+          sudo podman image rm ghcr.io/ublue-os/${{ env.image }}:${{ env.tag_version }}
+
+      - name: Rechunk Image
+        id: rechunk
+        uses: hhd-dev/rechunk@v0.6.2
+        with:
+          ref: "localhost/raw-img"
+          prev-ref: "ghcr.io/m2giles/m2os:${{ steps.generate_tags.outputs.default_tag }}"
+          version: "${{ env.version }}"
+          rechunk: "ghcr.io/hhd-dev/rechunk:latest"
+          labels: |
+            org.opencontainers.image.title=${{ env.IMAGE_NAME }}
+            org.opencontainers.image.description=m2os is my OCI image built from ublue projects. It mainly extends bazzite/bluefin for my uses.
+            org.opencontainers.image.version=${{ env.version }}
+            ostree.linux=${{ env.kernel_release }}.x86_64
+
+      - name: Load into Podman and Tag
+        shell: bash
+        run: |
+          IMAGE=$(podman pull ${{ steps.rechunk.outputs.ref }})
+          sudo rm -rf ${{ steps.rechunk.outputs.output }}
+          for tag in ${{ steps.generate_tags.outputs.alias_tags }}; do
+            podman tag $IMAGE m2os:$tag
+          done
+          podman tag $IMAGE rechunked-img
 
       - name: Check Secureboot
         id: secureboot
@@ -233,11 +234,15 @@ jobs:
             sudo apt update
             sudo apt install sbsigntool curl openssl
           fi
-          podman run --rm "${{ env.IMAGE_NAME }}":$(echo "${{ steps.generate_tags.outputs.build_tags }}" | cut -d " " -f 1) /bin/bash -c "cat /usr/lib/modules/*/vmlinuz" > vmlinuz
+          # podman run --rm "${{ env.IMAGE_NAME }}":$(echo "${{ steps.generate_tags.outputs.build_tags }}" | cut -d " " -f 1) /bin/bash -c "cat /usr/lib/modules/*/vmlinuz" > vmlinuz
+          podman run --rm rechunked-img /bin/bash -c "cat /usr/lib/modules/*/vmlinuz" > vmlinuz
           sbverify --list vmlinuz
-          curl -Lo akmods.der https://github.com/ublue-os/kernel-cache/raw/main/certs/public_key_2.der
+          curl --retry 3 -Lo kernel-sign.der https://github.com/ublue-os/kernel-cache/raw/main/certs/public_key.der
+          curl --retry 3 -Lo akmods.der https://github.com/ublue-os/kernel-cache/raw/main/certs/public_key_2.der
+          openssl x509 -in kernel-sign.der -out kernel-sign.crt
           openssl x509 -in akmods.der -out akmods.crt
-          sbverify --cert akmods.crt vmlinuz
+          sbverify --cert kernel-sign.crt vmlinuz || exit 1
+          sbverify --cert akmods.crt vmlinuz || exit 1
 
       - name: Lowercase Registry
         id: registry_case
@@ -257,8 +262,8 @@ jobs:
           attempt_limit: 3
           attempt_delay: 15000
           with: |
-            image: ${{ steps.build_image.outputs.image }}
-            tags: ${{ steps.build_image.outputs.tags }}
+            image: m2os
+            tags: ${{ steps.generate_tags.outputs.alias_tags }}
             registry: ${{ steps.registry_case.outputs.lowercase }}
             username: ${{ env.REGISTRY_USER }}
             password: ${{ env.REGISTRY_PASSWORD }}
